# Generated by Django 5.2.8 on 2025-12-01 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tripulacion', '0001_initial'),
        ('vuelo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionTripulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=100)),
                ('turno', models.CharField(max_length=50)),
                ('tripulate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripulacion.tripulacion')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelo.vuelo')),
            ],
        ),
    ]
