# Generated by Django 5.2.8 on 2025-12-01 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asientos', '0001_initial'),
        ('reserva', '0001_initial'),
        ('vuelo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detalle_reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clase', models.CharField(max_length=50)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asientos.asiento')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.reserva')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelo.vuelo')),
            ],
        ),
    ]
