# Generated by Django 5.2.8 on 2025-12-01 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vuelo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asiento', models.CharField(max_length=5)),
                ('tipo', models.CharField(choices=[('economico', 'Económico'), ('premium_economico', 'Premium Económico'), ('business', 'Business'), ('primera_clase', 'Primera Clase')], max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vuelo.vuelo')),
            ],
        ),
    ]
