# Generated by Django 5.2.8 on 2025-12-01 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aerolinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('pais_origen', models.CharField(max_length=100)),
                ('fecha_fundacion', models.DateField()),
                ('sitio_web', models.URLField()),
                ('telefono_contacto', models.CharField(max_length=15)),
            ],
        ),
    ]
