# Generated by Django 5.2.8 on 2025-12-01 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pieza', models.IntegerField()),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo', models.CharField(choices=[('equipaje_mano', 'Equipaje de Mano'), ('bodega', 'Equipaje de Bodega')], max_length=50)),
                ('costo_extra', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.reserva')),
            ],
        ),
    ]
