# Generated by Django 5.2.8 on 2025-12-01 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aerolinea', '0001_initial'),
        ('aeropuerto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vuelo', models.CharField(max_length=10)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField()),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('enbarcado', 'Enbarcado'), ('en_vuelo', 'En Vuelo'), ('aterrizado', 'Aterrizado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('duracion_estimada', models.DurationField()),
                ('distancia', models.IntegerField(help_text='Distancia en kilómetros')),
                ('aerolinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.aerolinea')),
                ('aeropuerto_llegada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_llegada', to='aeropuerto.aeropuerto')),
                ('aeropuerto_salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_salida', to='aeropuerto.aeropuerto')),
            ],
        ),
    ]
