# Generated by Django 5.2.8 on 2025-12-01 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aerolinea', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tripulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Piloto', 'Piloto'), ('Copiloto', 'Copiloto'), ('Auxiliar de Vuelo', 'Auxiliar de Vuelo'), ('Ingeniero de Vuelo', 'Ingeniero de Vuelo')], max_length=20)),
                ('licencia', models.CharField(max_length=50, unique=True)),
                ('fecha_contratacion', models.DateField()),
                ('aerolinea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aerolinea.aerolinea')),
            ],
        ),
    ]
